### PR TITLE
Changed Contributor list

### PR DESCRIPTION
**Pull request by AIGamesDeveloper**
The Aspect Inc. Contributor list was killing me so I took the time to change it.

### CODE REVIEW

**Review by GAMS2 — APPROVED** [review]
Go ahead.

**Comment by qloakongithub** [comment]
Lemme check.

**Comment by qloakongithub** [comment]
Seems almost fine, but why remove this?:

> We will be happy to help with all bugs and glitches that occur in AspectOS. We have different ways for you to reach out to us! We appreciate your feedback because not only does it help us by killing those pesky bugs and having a stable OS, you also have an experience like no other operating system (unless the operating system you're thinking about is real).

It seems fine.

**Review by DreamyCodes — COMMENTED** [review]
I, like qloak, think you should add back the part about bugs. other than that, though, it's fine.

**Comment by AIGamesDeveloper** [comment]
> I, like qloak, think you should add back the part about bugs. other than that, though, it's fine.

That was an accident

**Pull request merged**
