### PR TITLE
[Bugfix] Add decorative image to navbar and footer in 404.html

### PR DESCRIPTION
**Pull request by TheMowgliMan**
Add some fixes to the 404 page where the style didn't apply.

### CODE REVIEW

**Review by Skippy-the-derg — APPROVED** [review]
Looks...good? 
I don't understand reviewing, but it looks acceptable.

**Review by NILL2021 — COMMENTED** [review]
ebic

**Review by yoo832 — APPROVED** [review]
Go ahead!

**Review by AIGamesDeveloper — APPROVED** [review]
4 Approvals! Squashing and Merging now!

**Pull request merged**
