### PR TITLE
[appearance] Add Footer

### PR DESCRIPTION
**Pull request by Mbrick2**
Related #30 

image

PR made with [Github Online](github.dev)

### CODE REVIEW

**Comment by qloakongithub** [comment]
I don't really like the way this looks. It's just weird. I could try to make it look more natural.

**Comment by Mbrick2** [comment]
> I don't really like the way this looks. It's just weird.

In the GH Page Deployment it looks wrong. Here is the new Screenshot

image

**Review by yoo832 — APPROVED** [review]
Go ahead!

**Review by AIGamesDeveloper — APPROVED** [review]
I did state some things we could fix in the footer, but they are minor fixes. So I approve of this because we need a footer at the moment, and this is just the start. Eventually, we will improve this footer to have more links and better formatting. Good job!

**Pull request merged**
