### PR TITLE
[bugfix][apperance]Patch index.html

### PR DESCRIPTION
**Pull request by yoo832**
image

Someone put in a button script

### CODE REVIEW

**Review by AIGamesDeveloper — APPROVED** [review]
If that's the issue that I saw, then I approve. Kind of weird to have that there...

**Comment by qloakongithub** [comment]
I approve.

**Review by qloakongithub — APPROVED** [review]

**Review by Mbrick2 — APPROVED** [review]
Seems good

**Comment by AIGamesDeveloper** [comment]
One more approval...

**Pull request merged**
