### PR TITLE
[feature] Major Update which includes Dark Mode Toggle.

### PR DESCRIPTION
**Pull request by Mbrick2**
I know this is opinionated but this is what it does

- [x] Revert the background on the Navbar and Footer as it can cause people to have sensory issues

- [x] Remove the button from the footer on all pages (not just index.html) (#42)

- [x] Add a space between the Navbar and the Ukraine Banner #44 

- [x] Fix colors of some links

- [x] Add Dark Mode Toggle

### CODE REVIEW

**Comment by Mbrick2** [comment]
Tested on [Gituhb Pages](https://worstrickroll.github.io/aspectoshotfix/)

**Review by AIGamesDeveloper — APPROVED** [review]
This is some pretty good stuff! Hopefully, this works! I approve!

**Comment by Mbrick2** [comment]
> This is some pretty good stuff! Hopefully, this works! I approve!

Thanks.

**Comment by TheMowgliMan** [comment]
I approve of this. however, the original blurred img is for light mode, and the new one for dark mode. Did it accidentally carry over to light mode? You will need to get another image that is similar but dark for dark mode, as a solid color would be inconsistent. I forgot to make sure the Ukraine card wasn't just blue for light mode.

**Review by yoo832 — APPROVED** [review]
Hope it works! Go ahead!

**Review by AIGamesDeveloper — CHANGES_REQUESTED** [review]
Alright so I have reconsidered and there are some problems. When you are in dark mode, the footer font color is still black

Screenshot 2022-04-26 10 49 28 AM

And the "AspectOS" on the copyright date is white when light mode is enabled

Screenshot 2022-04-26 10 50 02 AM

**Comment by Mbrick2** [comment]
> Alright so I have reconsidered and there are some problems. When you are in dark mode, the footer font color is still black

Fixed

> Some of the pages seem to be missing BootStrap script tags

All of them have. Just they are before the footer

> You removed my pretty blurred image! I overrided it with a darker image in a media query below, so all you did was remove my image in light mode, not dark mode.

Fixed

> docs/index.html appears to have lost its /body tag

Fixed

**Review by TheMowgliMan — APPROVED** [review]
I approve now.

**Review by AIGamesDeveloper — CHANGES_REQUESTED** [review]
Alright so it looks better, but for me, the footer 

Screenshot 2022-04-27 7 41 40 AM
Screenshot 2022-04-27 7 41 50 AM
Screenshot 2022-04-27 7 42 01 AM

Some of the changes I requested still haven't been fixed

**Review by yoo832 — APPROVED** [review]
I had to review new changes,, Go ahead.

**Comment by Mbrick2** [comment]
> Some of the changes I requested still haven't been fixed

I see the issue

**Comment by Mbrick2** [comment]
@AIGamesDeveloper The bug has been resolved

**Comment by Mbrick2** [comment]
Does my vote count?

**Review by yoo832 — APPROVED** [review]
Again, had to view more files.

**Review by AIGamesDeveloper — APPROVED** [review]
As of right now, it's okay. If anything happens, just make an issue

And no, you cannot approve your own PR

**Comment by Mbrick2** [comment]
One more reviewer

**Review by qloakongithub — APPROVED** [review]
yes

**Review by NILL2021 — APPROVED** [review]
Nice

**Pull request merged**
