### PR TITLE
Dark Mode Addons

### PR DESCRIPTION
**Pull request by TheMowgliMan**
Added Dark Mode to the website. This uses a different decorative image for the header and footer for appearance. I also removed some redundant code, but that was lumped into the same commit.

EDIT: Added some screenshots.

Aspect OS - Home - Google Chrome 4_25_2022 11_33_43 AM
Aspect OS - Home - Google Chrome 4_25_2022 11_33_52 AM

### CODE REVIEW

**Review by DreamyCodes — APPROVED** [review]
Ooo, noice!

**Review by AIGamesDeveloper — COMMENTED** [review]
Great! But can dark mode only be enabled based on the user's theme settings?

**Review by Skippy-the-derg — APPROVED** [review]
NOICE! 👍

**Comment by TheMowgliMan** [comment]
Dark mode only works based on system settings/browser theme (based on
browser). Im not very good as JS so I used some CSS to pull it off.

Im on mobile, dont be suprised if this message is OOF

**Review by yoo832 — APPROVED** [review]
Go ahead! Also, can you add a button for it?

**Review by AIGamesDeveloper — APPROVED** [review]
I approve. This will be good for some people, but for us School Chromebook users, we will be blinded (not really)

Squashing and Merging...

**Pull request merged**
